### PR TITLE
Random .gitignore and GLIBC_SUPPORT -> GLIB_SUPPORT rename

### PR DESCRIPTION
**Pull request by ffainelli**

### CODE REVIEW

**Comment by ffainelli** [comment]
Ping? Does that look reasonable to you?

**Comment by spandruvada** [comment]
On Mon, 2015-02-09 at 15:26 -0800, Florian Fainelli wrote:
> Ping? Does that look reasonable to you?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 
Unfortunately not able to get time to review.

Thanks,
Srinivas

**Comment by ffainelli** [comment]
These are fairly trivial changes...

**Comment by spandruvada** [comment]
Thanks. Applied to development branch. During next revision these changes will be pulled in.

**Pull request closed without merging**
