### PR TITLE
Update to QCustomPlot 2.0.0-beta

### PR DESCRIPTION
**Pull request by Vogtinator**
Works with HiDPI and solves some other minor issues as well (see changelog.txt).

Builds and works fine on openSUSE Tumbleweed with Qt 5.7.1, I did not test other versions.

### CODE REVIEW

**Comment by spandruvada** [comment]
Thanks. I will test on Fedora and Ubuntu latest and then apply.

**Comment by Vogtinator** [comment]
Ping.

**Comment by spandruvada** [comment]
Tested on Ubuntu 16.04 with qt 5.8.

**Comment by spandruvada** [comment]
Merged ThermalMonitor changes.

**Pull request merged**
